module.exports = [
    { "city": "New York", "state": "New York" },
    { "city": "Los Angeles", "state": "California" },
    { "city": "Chicago", "state": "Illinois" },
    { "city": "Houston", "state": "Texas" },
    { "city": "Philadelphia", "state": "Pennsylvania" },
    { "city": "Phoenix", "state": "Arizona" },
    { "city": "San Diego", "state": "California" },
    { "city": "San Antonio", "state": "Texas" },
    { "city": "Dallas", "state": "Texas" },
    { "city": "Detroit", "state": "Michigan" },
    { "city": "San Jose", "state": "California" },
    { "city": "Indianapolis", "state": "Indiana" },
    { "city": "Jacksonville", "state": "Florida" },
    { "city": "San Francisco", "state": "California" },
    { "city": "Columbus", "state": "Ohio" },
    { "city": "Austin", "state": "Texas" },
    { "city": "Memphis", "state": "Tennessee" },
    { "city": "Baltimore", "state": "Maryland" },
    { "city": "Charlotte", "state": "North Carolina" },
    { "city": "Fort Worth", "state": "Texas" },
    { "city": "Boston", "state": "Massachusetts" },
    { "city": "Milwaukee", "state": "Wisconsin" },
    { "city": "El Paso", "state": "Texas" },
    { "city": "Washington", "state": "District of Columbia" },
    { "city": "Nashville-Davidson", "state": "Tennessee" },
    { "city": "Seattle", "state": "Washington" },
    { "city": "Denver", "state": "Colorado" },
    { "city": "Las Vegas", "state": "Nevada" },
    { "city": "Portland", "state": "Oregon" },
    { "city": "Oklahoma City", "state": "Oklahoma" },
    { "city": "Tucson", "state": "Arizona" },
    { "city": "Albuquerque", "state": "New Mexico" },
    { "city": "Atlanta", "state": "Georgia" },
    { "city": "Long Beach", "state": "California" },
    { "city": "Kansas City", "state": "Missouri" },
    { "city": "Fresno", "state": "California" },
    { "city": "New Orleans", "state": "Louisiana" },
    { "city": "Cleveland", "state": "Ohio" },
    { "city": "Sacramento", "state": "California" },
    { "city": "Mesa", "state": "Arizona" },
    { "city": "Virginia Beach", "state": "Virginia" },
    { "city": "Omaha", "state": "Nebraska" },
    { "city": "Colorado Springs", "state": "Colorado" },
    { "city": "Oakland", "state": "California" },
    { "city": "Miami", "state": "Florida" },
    { "city": "Tulsa", "state": "Oklahoma" },
    { "city": "Minneapolis", "state": "Minnesota" },
    { "city": "Honolulu", "state": "Hawaii" },
    { "city": "Arlington", "state": "Texas" },
    { "city": "Wichita", "state": "Kansas" },
    { "city": "St. Louis", "state": "Missouri" },
    { "city": "Raleigh", "state": "North Carolina" },
    { "city": "Santa Ana", "state": "California" },
    { "city": "Cincinnati", "state": "Ohio" },
    { "city": "Anaheim", "state": "California" },
    { "city": "Tampa", "state": "Florida" },
    { "city": "Toledo", "state": "Ohio" },
    { "city": "Pittsburgh", "state": "Pennsylvania" },
    { "city": "Aurora", "state": "Colorado" },
    { "city": "Bakersfield", "state": "California" },
    { "city": "Riverside", "state": "California" },
    { "city": "Stockton", "state": "California" },
    { "city": "Corpus Christi", "state": "Texas" },
    { "city": "Lexington-Fayette", "state": "Kentucky" },
    { "city": "Buffalo", "state": "New York" },
    { "city": "St. Paul", "state": "Minnesota" },
    { "city": "Anchorage", "state": "Alaska" },
    { "city": "Newark", "state": "New Jersey" },
    { "city": "Plano", "state": "Texas" },
    { "city": "Fort Wayne", "state": "Indiana" },
    { "city": "St. Petersburg", "state": "Florida" },
    { "city": "Glendale", "state": "Arizona" },
    { "city": "Lincoln", "state": "Nebraska" },
    { "city": "Norfolk", "state": "Virginia" },
    { "city": "Jersey City", "state": "New Jersey" },
    { "city": "Greensboro", "state": "North Carolina" },
    { "city": "Chandler", "state": "Arizona" },
    { "city": "Birmingham", "state": "Alabama" },
    { "city": "Henderson", "state": "Nevada" },
    { "city": "Scottsdale", "state": "Arizona" },
    { "city": "North Hempstead", "state": "New York" },
    { "city": "Madison", "state": "Wisconsin" },
    { "city": "Hialeah", "state": "Florida" },
    { "city": "Baton Rouge", "state": "Louisiana" },
    { "city": "Chesapeake", "state": "Virginia" },
    { "city": "Orlando", "state": "Florida" },
    { "city": "Lubbock", "state": "Texas" },
    { "city": "Garland", "state": "Texas" },
    { "city": "Akron", "state": "Ohio" },
    { "city": "Rochester", "state": "New York" },
    { "city": "Chula Vista", "state": "California" },
    { "city": "Reno", "state": "Nevada" },
    { "city": "Laredo", "state": "Texas" },
    { "city": "Durham", "state": "North Carolina" },
    { "city": "Modesto", "state": "California" },
    { "city": "Huntington", "state": "New York" },
    { "city": "Montgomery", "state": "Alabama" },
    { "city": "Boise", "state": "Idaho" },
    { "city": "Arlington", "state": "Virginia" },
    { "city": "San Bernardino", "state": "California" },
];